version: '3'

services:
  webs:
    image: webs
    build:
      context: . # path to docker dir in webs
    restart: on-failure:3
    container_name: webs
    environment:
      TZ: 'Europe/Prague'
      NETTE_DEVEL: '1' # Nette log level, 1 to enable
      MODE: 'dev' # dev/prod; prod default
    volumes:
      - ..:/var/www/html # path to webs repository
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf # site config
      - ./config/php.ini:/usr/local/etc/php/php-local.ini # site config
    ports:
      - 8080-8084:8080-8084 # opened ports mapping, not needed with proxy
    user: 1000:1000 # expects the main user with uid:pid
    extra_hosts: # enable the hack in apache.conf
      - "vyfuk.local:127.0.0.1"
      - "fykos.local:127.0.0.1"
      - "fol.local:127.0.0.1"
      - "fof.local:127.0.0.1"
      - "dsef.local:127.0.0.1"
