version: '3'

services:
  webs:
    image: ghcr.io/fykosak/webs:dev-docker
    container_name: webs
    restart: on-failure:3
    environment:
      TZ: 'Europe/Prague'
    volumes:
      - ./webs/:/var/www/html # path to webs repository
      - ./config/apache.conf:/etc/apache2/sites-available/000-default.conf # site config
      - ./config/local/:/var/www/html/app/config/local
      - ./temp/:/var/www/html/temp/
      - ./log/:/var/www/html/log/
      # photos
      - ./photos/dsef/:/www/html/www/dsef/photos/
      - ./photos/fof/:/www/html/www/fof/photos/
      - ./photos/fol/:/www/html/www/fol/photos/
      - ./photos/fykos/:/www/html/www/fykos/photos/
      - ./photos/vyfuk/:/www/html/www/vyfuk/photos/
    user: 1000:1000 # expects the main user with uid:pid
